### PR TITLE
Benching encode

### PR DESCRIPTION
**Pull request by lexman**
Hello,

here is a PR to keep track of the bench script to encode geometries. In order to save space, the list of geometries is stored in a zipped text file.

### CODE REVIEW

**Comment by rmarianski** [comment]
Looks like the tests are 7.7M for me, zipped. What do you think of putting this zip file in a public location on an s3 bucket? It would mean that it's harder for you to update, but it would be keep the repo check out size much smaller. I wouldn't expect that the actual list of geometries here would be changing very much anyway.

**Comment by rmarianski** [comment]
By the way, I get an error when running the entire file through the bench mark script, with python 2.7. Is that expected? (It works with just the first 10000 lines)

```
$ zcat bench/fgeoms.wkt.zip | python bench/bench_encode.py
Usage : zcat fgeoms.wkt.zip | head -10000 | python bench_encode.py
Creating layers with 10 shapes each
Running perf test
0 tiles produced
100 tiles produced
200 tiles produced
300 tiles produced
400 tiles produced
500 tiles produced
600 tiles produced
700 tiles produced
800 tiles produced
900 tiles produced
1000 tiles produced
1100 tiles produced
1200 tiles produced
1300 tiles produced
1400 tiles produced
1500 tiles produced
1600 tiles produced
1700 tiles produced
1800 tiles produced
1900 tiles produced
2000 tiles produced
Traceback (most recent call last):
  File "bench/bench_encode.py", line 55, in <module>
    run_test(layers)
  File "bench/bench_encode.py", line 41, in run_test
    res = encode(layer_description, on_invalid_geometry=on_invalid_geometry_ignore, round_fn=round)
  File "/home/rob/dev/python/mapbox-vector-tile/mapbox_vector_tile/__init__.py", line 21, in encode
    quantize_bounds, y_coord_down)
  File "/home/rob/dev/python/mapbox-vector-tile/mapbox_vector_tile/encoder.py", line 100, in addFeatures
    self.addFeature(feature, shape, y_coord_down)
  File "/home/rob/dev/python/mapbox-vector-tile/mapbox_vector_tile/encoder.py", line 233, in addFeature
    self._geo_encode(f, shape, y_coord_down)
  File "/home/rob/dev/python/mapbox-vector-tile/mapbox_vector_tile/encoder.py", line 444, in _geo_encode
    f.geometry.append((dy << 1) ^ (dy >> 31))
  File "/home/rob/dev/python/env/local/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 111, in append
    self._values.append(self._type_checker.CheckValue(value))
  File "/home/rob/dev/python/env/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 119, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: 159582692254
```

**Comment by lexman** [comment]
Hello,

I've put the zip on a gist and fixed the absurd coordinate. Now, only the python code is in the PR...

**Comment by rmarianski** [comment]
Thanks!

**Pull request merged**
