### PR TITLE
Updates of the repository

### PR DESCRIPTION
**Pull request by benoit9126**
Hi,

Here is a large proposal to update this Python package. It contains
1. ~The drop of Python 2 support~ #115 
2. ~A more recent generation of the `protobuf` Python code to solve #113 ~ #119
3. ~The usage of GitHub actions~ #116 
4. The usage of `Poetry` with a `pyproject.toml`
5. ~The usage of `pre-commit` (`black`, `isort`, `flake8`, etc)~ #121 
6. ~The usage of `tox` for the tests.~ #116

### CODE REVIEW

**Comment by vincentsarago** [comment]
@benoit9126 I'm not the repo owner or maintainer but IMO you should split this PR in multiple small PR and first discuss change in issue (e.g usage of poetry), it might ease the reviewer and increase the likelihood of the fix to be merged :-)

**Comment by benoit9126** [comment]
Ok. Do you have a priority order among the points listed above?

**Comment by benoit9126** [comment]
@rmarianski : The next possible steps would be:
1. A more recent generation of the `protobuf` Python code to solve #113 
2. The usage of `Poetry` with a `pyproject.toml`
3. The usage of pre-commit (black, isort, flake8, etc)

I start to implement the first which is the most important for me. If the community aggrees with the two other proposals, I can provide them too.

**Comment by benoit9126** [comment]
4. I also note that there are some troubles between the `round` function of Python 2 and 3 that forces you to use `quantize` and to pass a round function in some operators (`encode` for instance). As now, only Python 3 is supported, we could remove this argument `round_fn` and just use the round function.

**Comment by benoit9126** [comment]
@rmarianski I close this PR as everything was added in other PR.

**Pull request closed without merging**
