### PR TITLE
Usage of GHA instead of Travis

### PR DESCRIPTION
**Pull request by benoit9126**
Another part of #114

- Usage of GHA instead of Travis
- Tests are run for Python 3 versions only
- The dependencies were updated to fix some problems of dependencies (#113 for instance)

### CODE REVIEW

**Comment by benoit9126** [comment]
Is this repository still maintained? #113 starts to be really annoying as some other dependencies that I have in my project now depend on `protobuf>=4.21`

**Review by rmarianski — APPROVED** [review]
> Is this repository still maintained?

apologies, haven't been responsive here as of late. Thanks for the work to help move this forward :bow: 

I'm generally supportive of all your suggested changes. I'd prefer to first confirm that [we're ok with dropping python 2](https://github.com/tilezen/mapbox-vector-tile/pull/115#pullrequestreview-1218524312), and then we can merge that in. Following that, it'd be great if you could continue splitting off the changes you made in #114 into smaller prs.

**Comment by benoit9126** [comment]
@rmarianski Great! I can continue with additional PR after merging the two first #115 and #116

**Comment by rmarianski** [comment]
> @rmarianski Great! I can continue with additional PR after merging the two first #115 and #116

haven't heard any objections, and I went ahead and merged those prs. Thanks again :bow:

**Pull request merged**
